from __future__ import absolute_import
from __future__ import print_function
import os
import sys

from veriloggen.core.module import Module, StubModule
from veriloggen.fsm.fsm import FSM

script_dir = os.path.dirname(os.path.abspath(__file__))

# sha256_stream.v
with open(os.path.join(script_dir, "verilog/sha256/src/interfaces/stream/rtl/sha256_stream.v"), "r") as f:
    sha256_stream_v = f.read()
    
# sha256.v
with open(os.path.join(script_dir, "verilog/sha256/src/rtl/sha256.v"), "r") as f:
    sha256_v = f.read()

# sha256_core.v
with open(os.path.join(script_dir, "verilog/sha256/src/rtl/sha256_core.v"), "r") as f:
    sha256_core_v = f.read()
    
# sha256_k_constants.v
with open(os.path.join(script_dir, "verilog/sha256/src/rtl/sha256_k_constants.v"), "r") as f:
    sha256_k_constants_v = f.read()

# sha256_w_mem.v
with open(os.path.join(script_dir, "verilog/sha256/src/rtl/sha256_w_mem.v"), "r") as f:
    sha256_w_mem_v = f.read()

# TODO: Make sk generated by random number generator
SECRET_KEY = 0x597208cf39e5664c

class HmacSha256(object):
    
    __intrinsics__ = ('input_data', 'wait')
    
    def __init__(self, m: Module, name, clk, rst, sk=None):
        self.m = m
        self.name = name
        self.clk = clk
        self.rst = rst
        self.sk = SECRET_KEY if sk is None else sk
        
        self.s_tdata_i = self.m.Reg('s_tdata_i', 512)
        self.s_tlast_i = self.m.Reg('s_tlast_i')
        self.s_tvalid_i = self.m.Reg('s_tvalid_i')
        self.s_tready_o = self.m.Wire('s_tready_o')
        self.digest_o = self.m.Wire('digest_o', 256)
        self.digest_valid_o = self.m.Wire('digest_valid_o')
        self.mode = 1

        ports = [
            ('clk', clk),
            ('rst', rst),
            ('s_tdata_i', self.s_tdata_i),
            ('s_tlast_i', self.s_tlast_i),
            ('s_tvalid_i', self.s_tvalid_i),
            ('s_tready_o', self.s_tready_o),
            ('digest_o', self.digest_o),
            ('digest_valid_o', self.digest_valid_o),
            ('mode', self.mode),
        ]
        sha256_stream = StubModule('sha256_stream', sha256_stream_v)
        self.m.Instance(sha256_stream, 'sha256_stream', [], ports=ports)
        
        # TODO: Make it unnecessary to instantiate
        _sha256_core = StubModule('sha256_core', sha256_core_v)
        self.m.Instance(_sha256_core, 'inst_sha256_core', [], ports=[])
        _sha256_k_constants = StubModule('sha256_k_constants', sha256_k_constants_v)
        self.m.Instance(_sha256_k_constants, 'inst_sha256_k_constants', [], ports=[])
        _sha256_w_mem = StubModule('sha256_w_mem', sha256_w_mem_v)
        self.m.Instance(_sha256_w_mem, 'inst_sha256_w_mem', [], ports=[])
    
    def input_data(self, fsm: FSM, data, is_first, is_last):
        if is_first:
            # Add secret key to the beginning of the data
            fsm(
                self.s_tvalid_i(1),
                self.s_tlast_i(is_last),
                self.s_tdata_i(self.sk << 448),
            )
            fsm.goto_next(self.s_tvalid_i & self.s_tready_o)

            fsm(
                self.s_tvalid_i(1),
                self.s_tlast_i(is_last),
                self.s_tdata_i(data),
            )
            fsm.goto_next(self.s_tvalid_i & self.s_tready_o)
            
        else:
            fsm(
                self.s_tvalid_i(1),
                self.s_tlast_i(is_last),
                self.s_tdata_i(data),
            )
            fsm.goto_next(self.s_tvalid_i & self.s_tready_o)
        
        fsm(
            self.s_tvalid_i(0),
        )
        fsm.goto_next()
        
    def wait(self, fsm: FSM, digest):
        fsm.If(self.digest_valid_o)(
            digest(self.digest_o),
        )
        fsm.goto_next(self.digest_valid_o)
        
        
        
        
    
